version: '1.0'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
